config/routes.rb
Rails.application.routes.draw do
  root 'jobs#index'
  post 'jobs' => 'jobs#create'
  post 'webhook' => 'webhooks#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
  end

  def create
    JobCreationWorker.perform_async(params[:jobs].as_json)
    redirect_to root_path, flash: { success: 'Job created' }
  end
end

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    JobReportWorker.perform_async(params.as_json)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
  def default_bucket
    ::CfJobService::DEFAULT_BUCKET
  end

  def base_line_models
    [
      OpenStruct.new(id: 1, name: 'Object Detection for Self Driving Cars')
    ]
  end

  def use_cases
    [
      OpenStruct.new(id: 1, name: 'Single Shot Detector')
    ]
  end
end

app/views/jobs/index.html.slim
.row
  .panel.panel-primary
    .panel-heading
      | Training

    .panel-body
      = simple_form_for :jobs, url: jobs_path, method: :post do |f|
        .form-inputs
          .form-group
            = f.input :use_case, collection: use_cases, selected: 1
            = f.input :base_line_model, collection: base_line_models, selected: 1
            = f.input :bucket, input_html: { value: default_bucket }
            = f.input :path, placeholder: 'cf_job_data'

        .form-actions
            = f.button :submit, 'Train'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CfAlp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="b-layout thin <%= controller.controller_name %>">

    <div class="b-layout__container">
      <% flash.each do |message_type, message| %>
        <% if message_type=='error' %><div class="alert alert-danger"><%= message %></div><% end %>
        <% if message_type=='success' %><div class="alert alert-success"><%= message %></div><% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>